Repository dotnet/docs-aspire, pull requests merged in 2025-05, with the labels that each got.

#3217 Add Azure SQL integration articles
  docs/database/azure-sql-entity-framework-integration.md
  docs/database/azure-sql-integration.md
  docs/database/includes/azure-sql-hosting.md
  docs/database/includes/sql-server-client.md
  docs/database/includes/sql-server-ef-client.md
  docs/database/sql-server-entity-framework-integration.md
  docs/database/sql-server-integration.md
  docs/toc.yml
Labels: community-contribution

#3227 Fixed documentation to use the correct variable name
  docs/database/includes/azure-sql-hosting.md
Labels: community-contribution

#2846 add doc around dashboard telemetry
  docs/fundamentals/dashboard/microsoft-collected-dashboard-telemetry.md
  docs/toc.yml
Labels: fundamentals

#3390 Add explanatory notes to the EF Core Migrations tutorial.
  docs/database/ef-core-migrations.md
Labels: community-contribution

#3496 Update Seed data in database article to 9.2
  docs/database/seed-database-data.md
Labels: community-contribution

#3501 Update standalone-for-python.md
  docs/fundamentals/dashboard/standalone-for-python.md
Labels: community-contribution

#2539 Documentation for .NET Aspire RavenDB Integration
  docs/community-toolkit/overview.md
  docs/community-toolkit/ravendb.md
  docs/fundamentals/integrations-overview.md
  docs/toc.yml
Labels: fundamentals, community-contribution

#3666 Mention Adminer in SqlServer and Postgres Extensions
  docs/community-toolkit/hosting-postgresql-extensions.md
  docs/community-toolkit/hosting-sqlserver-extensions.md
Labels: community-contribution

#3667 Adding instructions and prompt
  .github/copilot-instructions.md
  .github/prompts/breaking-change.md
Labels: ⚙️ repo-maintenance
